# Generated by Django 5.1.3 on 2024-12-10 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_bankrupt'),
        ('transactions', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='accounts.userbankaccount'),
        ),
    ]
