# Generated by Django 5.1.3 on 2024-12-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transfer_sender_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='sender_account',
        ),
    ]
